<?xml version="1.0" encoding="UTF-8"?>
<ticket>
  <assigned-user-id type="integer">1366</assigned-user-id>
  <attachments-count type="integer">2</attachments-count>
  <closed type="boolean">true</closed>
  <created-at type="datetime">2008-08-14T22:37:00+01:00</created-at>
  <creator-id type="integer">1431</creator-id>
  <milestone-due-on type="datetime" nil="true"></milestone-due-on>
  <milestone-id type="integer" nil="true"></milestone-id>
  <number type="integer">835</number>
  <permalink>rescue_from-handlers-are-not-being-honored-in-functional-tests</permalink>
  <priority type="integer">8</priority>
  <project-id type="integer">8994</project-id>
  <raw-data type="binary" nil="true" encoding="base64"></raw-data>
  <state>resolved</state>
  <tag>2.1 actionpack bug controller edge patch tests</tag>
  <title>rescue_from handlers are not being honored in functional tests</title>
  <updated-at type="datetime">2008-10-04T18:47:34+01:00</updated-at>
  <user-id type="integer">17393</user-id>
  <version type="integer">10</version>
  <user-name>Repository</user-name>
  <creator-name>Mark Cornick</creator-name>
  <assigned-user-name>Pratik</assigned-user-name>
  <url>http://rails.lighthouseapp.com/projects/8994/tickets/835</url>
  <priority-name nil="true"></priority-name>
  <original-body>rescue_from handlers are not being honored in functional tests since commit 90c930f45c5c6766306929241462ffff8f67b86e.

Consider the following trivial controller and test, from a rails application created with the current edge code:

@@@ ruby
class ThingsController &lt; ApplicationController
  rescue_from ActiveRecord::RecordNotFound, :with =&gt; :record_not_found

  def show
    @thing = Thing.find(params[:id])
  end
  
  # ...
  
  private
  def record_not_found
    flash[:error] = 'That thing could not be found'
    redirect_to things_url
  end
end
@@@

@@@ ruby
require 'test_helper'

class ThingsControllerTest &lt; ActionController::TestCase
  test &quot;show with invalid id should set flash and redirect&quot; do
    get :show, :id =&gt; nil
    assert_equal 'That thing could not be found', flash[:error]
    assert_redirected_to things_url
  end
end
@@@

This functional test should pass because rescue_from should handle the ActiveRecord::RecordNotFound exception raised by Thing.find(nil). Instead, the exception falls through to the test, which aborts before hitting the assertions:

@@@
  1) Error:
test_show_with_invalid_id_should_set_flash_and_redirect(ThingsControllerTest):
ActiveRecord::RecordNotFound: Couldn't find Thing without an ID
@@@

The attached patch reverts a removal of rescue_action_with_handler that happened in commit 90c930f45c5c6766306929241462ffff8f67b86e. With this patch, the above test passes. However, I am not sure that this patch is the correct solution.</original-body>
  <latest-body>rescue_from handlers are not being honored in functional tests since commit 90c930f45c5c6766306929241462ffff8f67b86e.

Consider the following trivial controller and test, from a rails application created with the current edge code:

@@@ ruby
class ThingsController &lt; ApplicationController
  rescue_from ActiveRecord::RecordNotFound, :with =&gt; :record_not_found

  def show
    @thing = Thing.find(params[:id])
  end
  
  # ...
  
  private
  def record_not_found
    flash[:error] = 'That thing could not be found'
    redirect_to things_url
  end
end
@@@

@@@ ruby
require 'test_helper'

class ThingsControllerTest &lt; ActionController::TestCase
  test &quot;show with invalid id should set flash and redirect&quot; do
    get :show, :id =&gt; nil
    assert_equal 'That thing could not be found', flash[:error]
    assert_redirected_to things_url
  end
end
@@@

This functional test should pass because rescue_from should handle the ActiveRecord::RecordNotFound exception raised by Thing.find(nil). Instead, the exception falls through to the test, which aborts before hitting the assertions:

@@@
  1) Error:
test_show_with_invalid_id_should_set_flash_and_redirect(ThingsControllerTest):
ActiveRecord::RecordNotFound: Couldn't find Thing without an ID
@@@

The attached patch reverts a removal of rescue_action_with_handler that happened in commit 90c930f45c5c6766306929241462ffff8f67b86e. With this patch, the above test passes. However, I am not sure that this patch is the correct solution.</latest-body>
  <original-body-html>&lt;div&gt;&lt;p&gt;rescue_from handlers are not being honored in functional tests since commit 90c930f45c5c6766306929241462ffff8f67b86e.&lt;/p&gt;

&lt;p&gt;Consider the following trivial controller and test, from a rails application created with the current edge code:&lt;/p&gt;

&lt;pre&gt;&lt;code class=&quot;ruby&quot;&gt;
class ThingsController &amp;lt; ApplicationController
  rescue_from ActiveRecord::RecordNotFound, :with =&amp;gt; :record_not_found

  def show
    @thing = Thing.find(params[:id])
  end

  # ...

  private
  def record_not_found
    flash[:error] = 'That thing could not be found'
    redirect_to things_url
  end
end
&lt;/code&gt;&lt;/pre&gt;

&lt;pre&gt;&lt;code class=&quot;ruby&quot;&gt;
require 'test_helper'

class ThingsControllerTest &amp;lt; ActionController::TestCase
  test &amp;quot;show with invalid id should set flash and redirect&amp;quot; do
    get :show, :id =&amp;gt; nil
    assert_equal 'That thing could not be found', flash[:error]
    assert_redirected_to things_url
  end
end
&lt;/code&gt;&lt;/pre&gt;
&lt;p&gt;This functional test should pass because rescue_from should handle the ActiveRecord::RecordNotFound exception raised by Thing.find(nil). Instead, the exception falls through to the test, which aborts before hitting the assertions:&lt;/p&gt;

&lt;pre&gt;&lt;code&gt;
  1) Error:
test_show_with_invalid_id_should_set_flash_and_redirect(ThingsControllerTest):
ActiveRecord::RecordNotFound: Couldn't find Thing without an ID
&lt;/code&gt;&lt;/pre&gt;
&lt;p&gt;The attached patch reverts a removal of rescue_action_with_handler that happened in commit 90c930f45c5c6766306929241462ffff8f67b86e. With this patch, the above test passes. However, I am not sure that this patch is the correct solution.&lt;/p&gt;&lt;/div&gt;</original-body-html>
  <versions type="array">
    <version type="Ticket::Version">
      <assigned-user-id type="integer" nil="true"></assigned-user-id>
      <attachments-count type="integer">1</attachments-count>
      <body>rescue_from handlers are not being honored in functional tests since commit 90c930f45c5c6766306929241462ffff8f67b86e.

Consider the following trivial controller and test, from a rails application created with the current edge code:

@@@ ruby
class ThingsController &lt; ApplicationController
  rescue_from ActiveRecord::RecordNotFound, :with =&gt; :record_not_found

  def show
    @thing = Thing.find(params[:id])
  end
  
  # ...
  
  private
  def record_not_found
    flash[:error] = 'That thing could not be found'
    redirect_to things_url
  end
end
@@@

@@@ ruby
require 'test_helper'

class ThingsControllerTest &lt; ActionController::TestCase
  test &quot;show with invalid id should set flash and redirect&quot; do
    get :show, :id =&gt; nil
    assert_equal 'That thing could not be found', flash[:error]
    assert_redirected_to things_url
  end
end
@@@

This functional test should pass because rescue_from should handle the ActiveRecord::RecordNotFound exception raised by Thing.find(nil). Instead, the exception falls through to the test, which aborts before hitting the assertions:

@@@
  1) Error:
test_show_with_invalid_id_should_set_flash_and_redirect(ThingsControllerTest):
ActiveRecord::RecordNotFound: Couldn't find Thing without an ID
@@@

The attached patch reverts a removal of rescue_action_with_handler that happened in commit 90c930f45c5c6766306929241462ffff8f67b86e. With this patch, the above test passes. However, I am not sure that this patch is the correct solution.</body>
      <body-html>&lt;div&gt;&lt;p&gt;rescue_from handlers are not being honored in functional tests since commit 90c930f45c5c6766306929241462ffff8f67b86e.&lt;/p&gt;

&lt;p&gt;Consider the following trivial controller and test, from a rails application created with the current edge code:&lt;/p&gt;

&lt;pre&gt;&lt;code class=&quot;ruby&quot;&gt;
class ThingsController &amp;lt; ApplicationController
  rescue_from ActiveRecord::RecordNotFound, :with =&amp;gt; :record_not_found

  def show
    @thing = Thing.find(params[:id])
  end

  # ...

  private
  def record_not_found
    flash[:error] = 'That thing could not be found'
    redirect_to things_url
  end
end
&lt;/code&gt;&lt;/pre&gt;

&lt;pre&gt;&lt;code class=&quot;ruby&quot;&gt;
require 'test_helper'

class ThingsControllerTest &amp;lt; ActionController::TestCase
  test &amp;quot;show with invalid id should set flash and redirect&amp;quot; do
    get :show, :id =&amp;gt; nil
    assert_equal 'That thing could not be found', flash[:error]
    assert_redirected_to things_url
  end
end
&lt;/code&gt;&lt;/pre&gt;
&lt;p&gt;This functional test should pass because rescue_from should handle the ActiveRecord::RecordNotFound exception raised by Thing.find(nil). Instead, the exception falls through to the test, which aborts before hitting the assertions:&lt;/p&gt;

&lt;pre&gt;&lt;code&gt;
  1) Error:
test_show_with_invalid_id_should_set_flash_and_redirect(ThingsControllerTest):
ActiveRecord::RecordNotFound: Couldn't find Thing without an ID
&lt;/code&gt;&lt;/pre&gt;
&lt;p&gt;The attached patch reverts a removal of rescue_action_with_handler that happened in commit 90c930f45c5c6766306929241462ffff8f67b86e. With this patch, the above test passes. However, I am not sure that this patch is the correct solution.&lt;/p&gt;&lt;/div&gt;</body-html>
      <closed type="boolean">false</closed>
      <created-at type="datetime">2008-08-14T22:37:00+01:00</created-at>
      <creator-id type="integer">1431</creator-id>
      <diffable-attributes type="yaml">--- {}

</diffable-attributes>
      <milestone-id type="integer">9903</milestone-id>
      <number type="integer">835</number>
      <permalink>rescue_from-handlers-are-not-being-honored-in-functional-tests</permalink>
      <priority type="integer">0</priority>
      <project-id type="integer">8994</project-id>
      <state>new</state>
      <tag>2.1 actionpack bug controller patch tests</tag>
      <title>rescue_from handlers are not being honored in functional tests</title>
      <updated-at type="datetime">2008-08-14T22:37:00+01:00</updated-at>
      <user-id type="integer">1431</user-id>
      <version type="integer">1</version>
      <user-name>Mark Cornick</user-name>
      <creator-name>Mark Cornick</creator-name>
      <assigned-user-name nil="true"></assigned-user-name>
      <url>http://rails.lighthouseapp.com/projects/8994/tickets/835</url>
      <priority-name nil="true"></priority-name>
      <milestone-title>2.x</milestone-title>
    </version>
    <version type="Ticket::Version">
      <assigned-user-id type="integer" nil="true"></assigned-user-id>
      <attachments-count type="integer">1</attachments-count>
      <body>+1

Ah ha!  I just had this happen, thanks for the patch!</body>
      <body-html>&lt;div&gt;&lt;p&gt;+1&lt;/p&gt;

&lt;p&gt;Ah ha!  I just had this happen, thanks for the patch!&lt;/p&gt;&lt;/div&gt;</body-html>
      <closed type="boolean">false</closed>
      <created-at type="datetime">2008-08-14T22:58:40+01:00</created-at>
      <creator-id type="integer">1431</creator-id>
      <diffable-attributes type="yaml">--- 
:tag: 2.1 actionpack bug controller patch tests
</diffable-attributes>
      <milestone-id type="integer">9903</milestone-id>
      <number type="integer">835</number>
      <permalink>rescue_from-handlers-are-not-being-honored-in-functional-tests</permalink>
      <priority type="integer">0</priority>
      <project-id type="integer">8994</project-id>
      <state>new</state>
      <tag>actionpack bug controller edge patch tests</tag>
      <title>rescue_from handlers are not being honored in functional tests</title>
      <updated-at type="datetime">2008-08-14T22:58:40+01:00</updated-at>
      <user-id type="integer">16961</user-id>
      <version type="integer">2</version>
      <user-name>Matt Swasey</user-name>
      <creator-name>Mark Cornick</creator-name>
      <assigned-user-name nil="true"></assigned-user-name>
      <url>http://rails.lighthouseapp.com/projects/8994/tickets/835</url>
      <priority-name nil="true"></priority-name>
      <milestone-title>2.x</milestone-title>
    </version>
    <version type="Ticket::Version">
      <assigned-user-id type="integer" nil="true"></assigned-user-id>
      <attachments-count type="integer">1</attachments-count>
      <body>if you remove overridden 'rescue_action' in your functional test, it should work as expected.</body>
      <body-html>&lt;div&gt;&lt;p&gt;if you remove overridden 'rescue_action' in your functional test, it should work as expected.&lt;/p&gt;&lt;/div&gt;</body-html>
      <closed type="boolean">true</closed>
      <created-at type="datetime">2008-08-21T12:00:11+01:00</created-at>
      <creator-id type="integer">1431</creator-id>
      <diffable-attributes type="yaml">--- 
:state: new
:tag: actionpack bug controller edge patch tests
</diffable-attributes>
      <milestone-id type="integer">9903</milestone-id>
      <number type="integer">835</number>
      <permalink>rescue_from-handlers-are-not-being-honored-in-functional-tests</permalink>
      <priority type="integer">0</priority>
      <project-id type="integer">8994</project-id>
      <state>invalid</state>
      <tag>2.1 actionpack bug controller edge patch tests</tag>
      <title>rescue_from handlers are not being honored in functional tests</title>
      <updated-at type="datetime">2008-08-21T12:00:11+01:00</updated-at>
      <user-id type="integer">1366</user-id>
      <version type="integer">3</version>
      <user-name>Pratik</user-name>
      <creator-name>Mark Cornick</creator-name>
      <assigned-user-name nil="true"></assigned-user-name>
      <url>http://rails.lighthouseapp.com/projects/8994/tickets/835</url>
      <priority-name nil="true"></priority-name>
      <milestone-title>2.x</milestone-title>
    </version>
    <version type="Ticket::Version">
      <assigned-user-id type="integer" nil="true"></assigned-user-id>
      <attachments-count type="integer">1</attachments-count>
      <body>@@@ ruby
# Re-raise errors caught by the controller.
class ThingsController; def rescue_action(e) raise e end; end
@@@

The test posted above, as well as the tests in my current application that exposed this bug, do not contain these lines, and do not override rescue_action.

In other words, this is *not* the same issue as #664.</body>
      <body-html>&lt;div&gt;&lt;pre&gt;&lt;code class=&quot;ruby&quot;&gt;
# Re-raise errors caught by the controller.
class ThingsController; def rescue_action(e) raise e end; end
&lt;/code&gt;&lt;/pre&gt;
&lt;p&gt;The test posted above, as well as the tests in my current application that exposed this bug, do not contain these lines, and do not override rescue_action.&lt;/p&gt;

&lt;p&gt;In other words, this is &lt;em&gt;not&lt;/em&gt; the same issue as &lt;a href=&quot;/projects/8994/tickets/664&quot; title=&quot;Ticket #664&quot;&gt;#664&lt;/a&gt;.&lt;/p&gt;&lt;/div&gt;</body-html>
      <closed type="boolean">true</closed>
      <created-at type="datetime">2008-08-21T12:58:40+01:00</created-at>
      <creator-id type="integer">1431</creator-id>
      <diffable-attributes type="yaml">--- {}

</diffable-attributes>
      <milestone-id type="integer">9903</milestone-id>
      <number type="integer">835</number>
      <permalink>rescue_from-handlers-are-not-being-honored-in-functional-tests</permalink>
      <priority type="integer">0</priority>
      <project-id type="integer">8994</project-id>
      <state>invalid</state>
      <tag>2.1 actionpack bug controller edge patch tests</tag>
      <title>rescue_from handlers are not being honored in functional tests</title>
      <updated-at type="datetime">2008-08-21T12:58:40+01:00</updated-at>
      <user-id type="integer">1431</user-id>
      <version type="integer">4</version>
      <user-name>Mark Cornick</user-name>
      <creator-name>Mark Cornick</creator-name>
      <assigned-user-name nil="true"></assigned-user-name>
      <url>http://rails.lighthouseapp.com/projects/8994/tickets/835</url>
      <priority-name nil="true"></priority-name>
      <milestone-title>2.x</milestone-title>
    </version>
    <version type="Ticket::Version">
      <assigned-user-id type="integer" nil="true"></assigned-user-id>
      <attachments-count type="integer">1</attachments-count>
      <body>Lighthouse ate the text before my code block, which read:

&quot;I assume you are referring to lines such as the following, which are present in tests generated by very old versions of the scaffold generator:&quot;</body>
      <body-html>&lt;div&gt;&lt;p&gt;Lighthouse ate the text before my code block, which read:&lt;/p&gt;

&lt;p&gt;&quot;I assume you are referring to lines such as the following, which are present in tests generated by very old versions of the scaffold generator:&quot;&lt;/p&gt;&lt;/div&gt;</body-html>
      <closed type="boolean">true</closed>
      <created-at type="datetime">2008-08-21T12:59:53+01:00</created-at>
      <creator-id type="integer">1431</creator-id>
      <diffable-attributes type="yaml">--- {}

</diffable-attributes>
      <milestone-id type="integer">9903</milestone-id>
      <number type="integer">835</number>
      <permalink>rescue_from-handlers-are-not-being-honored-in-functional-tests</permalink>
      <priority type="integer">0</priority>
      <project-id type="integer">8994</project-id>
      <state>invalid</state>
      <tag>2.1 actionpack bug controller edge patch tests</tag>
      <title>rescue_from handlers are not being honored in functional tests</title>
      <updated-at type="datetime">2008-08-21T12:59:53+01:00</updated-at>
      <user-id type="integer">1431</user-id>
      <version type="integer">5</version>
      <user-name>Mark Cornick</user-name>
      <creator-name>Mark Cornick</creator-name>
      <assigned-user-name nil="true"></assigned-user-name>
      <url>http://rails.lighthouseapp.com/projects/8994/tickets/835</url>
      <priority-name nil="true"></priority-name>
      <milestone-title>2.x</milestone-title>
    </version>
    <version type="Ticket::Version">
      <assigned-user-id type="integer" nil="true"></assigned-user-id>
      <attachments-count type="integer">1</attachments-count>
      <body>Oops. My bad. Could you please attach a failing test case or steps to reproduce ?

Thanks.</body>
      <body-html>&lt;div&gt;&lt;p&gt;Oops. My bad. Could you please attach a failing test case or steps to reproduce ?&lt;/p&gt;

&lt;p&gt;Thanks.&lt;/p&gt;&lt;/div&gt;</body-html>
      <closed type="boolean">true</closed>
      <created-at type="datetime">2008-08-21T13:04:56+01:00</created-at>
      <creator-id type="integer">1431</creator-id>
      <diffable-attributes type="yaml">--- {}

</diffable-attributes>
      <milestone-id type="integer">9903</milestone-id>
      <number type="integer">835</number>
      <permalink>rescue_from-handlers-are-not-being-honored-in-functional-tests</permalink>
      <priority type="integer">0</priority>
      <project-id type="integer">8994</project-id>
      <state>invalid</state>
      <tag>2.1 actionpack bug controller edge patch tests</tag>
      <title>rescue_from handlers are not being honored in functional tests</title>
      <updated-at type="datetime">2008-08-21T13:04:56+01:00</updated-at>
      <user-id type="integer">1366</user-id>
      <version type="integer">6</version>
      <user-name>Pratik</user-name>
      <creator-name>Mark Cornick</creator-name>
      <assigned-user-name nil="true"></assigned-user-name>
      <url>http://rails.lighthouseapp.com/projects/8994/tickets/835</url>
      <priority-name nil="true"></priority-name>
      <milestone-title>2.x</milestone-title>
    </version>
    <version type="Ticket::Version">
      <assigned-user-id type="integer" nil="true"></assigned-user-id>
      <attachments-count type="integer">2</attachments-count>
      <body>The attachment has a controller, functional test, and enough Rails infrastructure to demonstrate the bug.

Steps to reproduce:
1) unzip the code
2) install rails 2.1.0 gem or freeze rails 2.1.0 into vendor
3) rake test:functionals

Expected: test_show_with_invalid_id_should_set_flash should pass
Actual: test_show_with_invalid_id_should_set_flash passes

4) git clone current edge rails into vendor
5) rake test:functionals

Expected: test_show_with_invalid_id_should_set_flash should pass
Actual: test_show_with_invalid_id_should_set_flash raises an unhandled ActiveRecord::RecordNotFound exception and aborts</body>
      <body-html>&lt;div&gt;&lt;p&gt;The attachment has a controller, functional test, and enough Rails infrastructure to demonstrate the bug.&lt;/p&gt;

&lt;p&gt;Steps to reproduce:
1) unzip the code
2) install rails 2.1.0 gem or freeze rails 2.1.0 into vendor
3) rake test:functionals&lt;/p&gt;

&lt;p&gt;Expected: test_show_with_invalid_id_should_set_flash should pass
Actual: test_show_with_invalid_id_should_set_flash passes&lt;/p&gt;

&lt;p&gt;4) git clone current edge rails into vendor
5) rake test:functionals&lt;/p&gt;

&lt;p&gt;Expected: test_show_with_invalid_id_should_set_flash should pass
Actual: test_show_with_invalid_id_should_set_flash raises an unhandled ActiveRecord::RecordNotFound exception and aborts&lt;/p&gt;&lt;/div&gt;</body-html>
      <closed type="boolean">true</closed>
      <created-at type="datetime">2008-08-21T16:23:09+01:00</created-at>
      <creator-id type="integer">1431</creator-id>
      <diffable-attributes type="yaml">--- {}

</diffable-attributes>
      <milestone-id type="integer">9903</milestone-id>
      <number type="integer">835</number>
      <permalink>rescue_from-handlers-are-not-being-honored-in-functional-tests</permalink>
      <priority type="integer">0</priority>
      <project-id type="integer">8994</project-id>
      <state>invalid</state>
      <tag>2.1 actionpack bug controller edge patch tests</tag>
      <title>rescue_from handlers are not being honored in functional tests</title>
      <updated-at type="datetime">2008-08-21T16:23:09+01:00</updated-at>
      <user-id type="integer">1431</user-id>
      <version type="integer">7</version>
      <user-name>Mark Cornick</user-name>
      <creator-name>Mark Cornick</creator-name>
      <assigned-user-name nil="true"></assigned-user-name>
      <url>http://rails.lighthouseapp.com/projects/8994/tickets/835</url>
      <priority-name nil="true"></priority-name>
      <milestone-title>2.x</milestone-title>
    </version>
    <version type="Ticket::Version">
      <assigned-user-id type="integer">1366</assigned-user-id>
      <attachments-count type="integer">2</attachments-count>
      <body></body>
      <body-html></body-html>
      <closed type="boolean">true</closed>
      <created-at type="datetime">2008-08-21T16:45:06+01:00</created-at>
      <creator-id type="integer">1431</creator-id>
      <diffable-attributes type="yaml">--- 
:state: invalid
:assigned_user: 
</diffable-attributes>
      <milestone-id type="integer">9903</milestone-id>
      <number type="integer">835</number>
      <permalink>rescue_from-handlers-are-not-being-honored-in-functional-tests</permalink>
      <priority type="integer">0</priority>
      <project-id type="integer">8994</project-id>
      <state>incomplete</state>
      <tag>2.1 actionpack bug controller edge patch tests</tag>
      <title>rescue_from handlers are not being honored in functional tests</title>
      <updated-at type="datetime">2008-08-21T16:45:06+01:00</updated-at>
      <user-id type="integer">1366</user-id>
      <version type="integer">8</version>
      <user-name>Pratik</user-name>
      <creator-name>Mark Cornick</creator-name>
      <assigned-user-name>Pratik</assigned-user-name>
      <url>http://rails.lighthouseapp.com/projects/8994/tickets/835</url>
      <priority-name nil="true"></priority-name>
      <milestone-title>2.x</milestone-title>
    </version>
    <version type="Ticket::Version">
      <assigned-user-id type="integer">1366</assigned-user-id>
      <attachments-count type="integer">2</attachments-count>
      <body>ActionController::TestCase is overriding rescue_action, causing this issue.</body>
      <body-html>&lt;div&gt;&lt;p&gt;ActionController::TestCase is overriding rescue_action, causing
this issue.&lt;/p&gt;&lt;/div&gt;</body-html>
      <closed type="boolean">false</closed>
      <created-at type="datetime">2008-09-30T01:33:08+01:00</created-at>
      <creator-id type="integer">1431</creator-id>
      <diffable-attributes type="yaml">--- 
:state: incomplete
:milestone: 9903
:tag: 2.1 actionpack bug controller edge patch tests
</diffable-attributes>
      <milestone-id type="integer" nil="true"></milestone-id>
      <number type="integer">835</number>
      <permalink>rescue_from-handlers-are-not-being-honored-in-functional-tests</permalink>
      <priority type="integer">0</priority>
      <project-id type="integer">8994</project-id>
      <state>open</state>
      <tag>&quot;2.1&quot; actionpack bug controller edge patch tests</tag>
      <title>rescue_from handlers are not being honored in functional tests</title>
      <updated-at type="datetime">2008-09-30T01:33:10+01:00</updated-at>
      <user-id type="integer">1366</user-id>
      <version type="integer">9</version>
      <user-name>Pratik</user-name>
      <creator-name>Mark Cornick</creator-name>
      <assigned-user-name>Pratik</assigned-user-name>
      <url>http://rails.lighthouseapp.com/projects/8994/tickets/835</url>
      <priority-name nil="true"></priority-name>
      <milestone-title nil="true"></milestone-title>
    </version>
    <version type="Ticket::Version">
      <assigned-user-id type="integer">1366</assigned-user-id>
      <attachments-count type="integer">2</attachments-count>
      <body>(from [5e3517ea7b9fbd460f772bffc9212d882011f2bc]) Ensure rescue_from handlers are respected inside tests. [#835 state:resolved]

Note : If you're not using rescue_from, you should overrider rescue_action_without_handler() method
and not rescue_action(). Afterwards, you can set request.remote_addr to a non &quot;0.0.0.0&quot; value for testing the
overridden behavior.
http://github.com/rails/rails/commit/5e3517ea7b9fbd460f772bffc9212d882011f2bc</body>
      <body-html>&lt;div&gt;&lt;p&gt;(from [5e3517ea7b9fbd460f772bffc9212d882011f2bc]) Ensure
rescue_from handlers are respected inside tests. [&lt;a href=&quot;/projects/8994/tickets/835&quot; title=&quot;Ticket #835&quot;&gt;#835&lt;/a&gt;
state:resolved]&lt;/p&gt;
&lt;p&gt;Note : If you're not using rescue_from, you should overrider
rescue_action_without_handler() method and not rescue_action().
Afterwards, you can set request.remote_addr to a non &quot;0.0.0.0&quot;
value for testing the overridden behavior. &lt;a href=&quot;http://github.com/rails/rails/commit/5e3517ea7b9fbd460f772bffc9212d882011f2bc&quot;&gt;
http://github.com/rails/rails/co...&lt;/a&gt;&lt;/p&gt;&lt;/div&gt;</body-html>
      <closed type="boolean">true</closed>
      <created-at type="datetime">2008-10-04T18:47:32+01:00</created-at>
      <creator-id type="integer">1431</creator-id>
      <diffable-attributes type="yaml">--- 
:state: open
</diffable-attributes>
      <milestone-id type="integer" nil="true"></milestone-id>
      <number type="integer">835</number>
      <permalink>rescue_from-handlers-are-not-being-honored-in-functional-tests</permalink>
      <priority type="integer">0</priority>
      <project-id type="integer">8994</project-id>
      <state>resolved</state>
      <tag>&quot;2.1&quot; actionpack bug controller edge patch tests</tag>
      <title>rescue_from handlers are not being honored in functional tests</title>
      <updated-at type="datetime">2008-10-04T18:47:34+01:00</updated-at>
      <user-id type="integer">17393</user-id>
      <version type="integer">10</version>
      <user-name>Repository</user-name>
      <creator-name>Mark Cornick</creator-name>
      <assigned-user-name>Pratik</assigned-user-name>
      <url>http://rails.lighthouseapp.com/projects/8994/tickets/835</url>
      <priority-name nil="true"></priority-name>
      <milestone-title nil="true"></milestone-title>
    </version>
  </versions>
  <attachments type="array">
    <attachment type="Attachment">
      <code>3ada92756becfbb8d16447dffab2262cf3c5876b</code>
      <content-type>text/plain</content-type>
      <created-at type="datetime">2008-08-14T22:37:00+01:00</created-at>
      <filename>perform_action_with_rescue.diff</filename>
      <height type="integer" nil="true"></height>
      <id type="integer">39324</id>
      <size type="integer">566</size>
      <uploader-id type="integer">1431</uploader-id>
      <width type="integer" nil="true"></width>
      <url>http://rails.lighthouseapp.com/attachments/39324/perform_action_with_rescue.diff</url>
    </attachment>
    <attachment type="Attachment">
      <code>70da0aca848cc4c89d50bc5c78b7111d368ee2e0</code>
      <content-type>application/zip</content-type>
      <created-at type="datetime">2008-08-21T16:23:09+01:00</created-at>
      <filename>test-case-835.zip</filename>
      <height type="integer" nil="true"></height>
      <id type="integer">40733</id>
      <size type="integer">8706</size>
      <uploader-id type="integer">1431</uploader-id>
      <width type="integer" nil="true"></width>
      <url>http://rails.lighthouseapp.com/attachments/40733/test-case-835.zip</url>
    </attachment>
  </attachments>
</ticket>
